paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Products
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      tags:
        - Products
      responses:
        '201':
          description: Producto creado
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
    put:
      summary: Actualizar un producto por ID
      tags:
        - Products
      responses:
        '200':
          description: Producto actualizado
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
    delete:
      summary: Eliminar un producto por ID
      tags:
        - Products
      responses:
        '200':
          description: Producto eliminado
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number